### ISSUE TITLE
Missing `loads` and `load` definitions in `__init__.pyi`

### ISSUE THREAD

**Issue by kifuan** [TkTech/pysimdjson#103]
I know it is defined in `__init__.py`, but it seems that PyCharm only analyzes `__init__.pyi`, where `loads` is not defined.

Maybe I could create a PR to fix this tiny problem if you appreciate it.

![image](https://user-images.githubusercontent.com/61240774/211129047-ce92ccd5-d5ee-4b40-b413-4ca4a0414f5c.png)

**Comment by kifuan** [comment]
The same as `load` function.

**Comment by lemire** [comment]
@kifuan Would you prepare a pull request? I am sure it would be considered.

**Comment by kifuan** [comment]
Sure, there are two ways.

1. Copy the declarations in `__init__.py`, like the code below:

```py
def loads(s, *, cls=None, object_hook=None, parse_float=None, parse_int=None,
          parse_constant=None, object_pairs_hook=None, **kwargs):
  ...
```

2. Use `json.load`, `json.loads`.

```py
loads = json.loads
load = json.load
```

As `__init__.pyi` is only an interface that will not be executed, it works properly.

![image](https://user-images.githubusercontent.com/61240774/211831992-39d1abed-802f-4b7d-b22e-1a291148fe81.png)

**Comment by kifuan** [comment]
But I prefer the first way, which will not confuse users.

**Comment by lemire** [comment]
Can't this be done automatically...

https://www.mypy-lang.org

**Comment by TkTech** [comment]
> Can't this be done automatically...
> 
> https://www.mypy-lang.org

Automatic generation doesn't work terribly well with native extensions.

**Comment by TkTech** [comment]
> Use `json.load`, `json.loads`.

We don't have a 1:1 interface with `json.load/s`, so this would result in incorrect signatures.

**Comment by kifuan** [comment]
Is `__init__.pyi` generated or written manually? It doesn't look like a generated file.
