### ISSUE TITLE
Return a default value from at_pointer when the key doesn't exist

### ISSUE THREAD

**Issue by ELind77** [TkTech/pysimdjson#105]
I'd like to request a feature to return a default value from `at_pointer` when the path doesn't exist rather than throwing a key error. This is especially important when parsing data with a mixed schema--e.g. application log/data that have changed schema over time.  

Not throwing and catching the error could save significant time as Python error handling isn't especially performant and it would give users more flexibility to decide how to handle missing keys/values.

**Comment by TkTech** [comment]
Completed in #110.
