### ISSUE TITLE
Can pysimdjson parse in streaming mode?

### ISSUE THREAD

**Issue by theogaraj** [TkTech/pysimdjson#120]
Hello, thank you for your work!  I've just started experimenting with this library.  

I am attempting to parse larger-than-memory JSON files, and was wondering if pysimdjson supports stream-based parsing of JSON documents (similar to [jsonslicer](https://pypi.org/project/jsonslicer/)) or [ijson](https://pypi.org/project/ijson/))?

I couldn't find anything in the documentation that suggests this, but am hoping there's some way to do this.

**Comment by theogaraj** [comment]
Browsing through other issues I see that the answer in 2021 was "no" (https://github.com/TkTech/pysimdjson/issues/86#issuecomment-904847976)

Is this still the case?

**Comment by TkTech** [comment]
Unfortunately the underlying simdjson library does not yet have support for a SAX-style parser. See https://github.com/simdjson/simdjson/issues/128 for future updates.
