### ISSUE TITLE
Expand simdjson.pxd to have 1:1 coverage of simdjson's API

### ISSUE THREAD

**Issue by TkTech** [TkTech/pysimdjson#13]
Currently we only expose the minimum of simdjson's API to support `loads()` and `items()`' query "language". We should aim for 1:1 so that this library can be used to:

- explore simdjson features outside of our limited functionality
- quickly expand the test coverage of simdjson itself by writing high-level tests in Python
- 3rd party projects that want to use simdjson and not pysimdjson should be able to just import our .pxd to get "free" bindings
- ideally @lemire and @geofflangdale themselves should find it more enjoyable and efficient to test new features and changes for simdjson using pysimdjson. `pysimdjson shell canada.json` should give you a Python shell with the `ParsedJson` and a `Iterator` object already setup.

**Comment by geofflangdale** [comment]
I like Python, and would not be averse to seeing this. It's even possible that features _beyond_ the current simdjson API could be prototyped in Python. Given the way Python works (to my limited understanding) it might not be hard at all to build a seamless-looking API that defers things like string normalization and number parsing to be on-demand.

**Comment by TkTech** [comment]
@geofflangdale I've pushed the changes so far to master but have not yet released them as they're missing test coverage. Could you take a look at https://pysimdjson.tkte.ch/#api-reference if you have a chance to see if any of the documentation is outright wrong?

This should be everything that's public in ParsedJson and Iterator. `get_corpus` isn't useful, as that interface needs to handle Python-land input.

I'm going to create a 3rd top-level object called `Tape` that will just add an abstraction around the Tape arrays, so that things like this are pretty clean:

```python
with open("bigjson.json", "rb") as source:
    pj = ParsedJson(source)
    print(pj.tape[5].type_)
```

and accessing things outside the tape would raise `IndexError` as expected. Writing a tape from scratch should also be simple. `pj.tape += 6` should append an integer to the tape. `pj.tape += "xyz"` appends a string, etc...

**Comment by geofflangdale** [comment]
Obviously you are aware of the potential change in the semantics of move_forward that's coming up. :-)

This looks fine. I am hesitant about a couple of the API calls and functionality things - items() should make it clear that simdjson is _still_ doing an entire parse of the JSON at the API level. Otherwise people will measure this and assume we are doing Mison-style partial scans (badly).

Modifying the tape is a can of worms. It's not really meant to be a mutable structure for better or worse.

**Comment by TkTech** [comment]
Agreed, items definitely needs clarification and expansion. I'll add it in the morning.

Agreed on the tape as well, I'll ensure it's implemented so adding mutability isn't a headache down the road but still implement the RO interface. Needed to support the debug command in #14.

> Given the way Python works (to my limited understanding) it might not be hard at all to build a seamless-looking API that defers things like string normalization and number parsing to be on-demand.

This is pretty simple with regular python objects, and with the C API we can create truly transparent deferral, consumer would have no idea.
