### ISSUE TITLE
Installation report exception

### ISSUE THREAD

**Issue by lvorcool** [TkTech/pysimdjson#15]
My local environment：
python3.6
macos mojave 10.14.3

When I use this installation method `pip install pysimdjson`
Error exception：
![image](https://user-images.githubusercontent.com/21286480/53480531-5ff71d00-3ab6-11e9-941f-c63331b378e3.png)

When I use this installation method
 `git clone https://github.com/TkTech/pysimdjson.git
  cd pysimdjson
 python setup.py install`
Error exception：
![image](https://user-images.githubusercontent.com/21286480/53480606-8026dc00-3ab6-11e9-9ab5-21e6fc8fd9bf.png)

Please help me to see this installation problem, thank you

**Comment by lemire** [comment]
Does the following helps?
https://github.com/TkTech/pysimdjson/issues/17

**Comment by TkTech** [comment]
@lvorcool this one isn't pysimdjson, you don't have xcode installed (or it's reaaaaaal old). Run `xcode-select --install`.
