### ISSUE TITLE
API compatibility with python's json module

### ISSUE THREAD

**Issue by mosajjal** [TkTech/pysimdjson#20]
Hi, I just tested this library and I was very impressed with the way it quickly loaded my JSON lines into dicts. however, I found some incompatibilities with the default `json` module and `pysimdjson`. For example, `json` module accepts strings to load as opposed to `pysimdjson` which only accepts `bytes`. Also, there's no dumps function.

Is it advisable to make a fully compatible library as a drop-in replacement for `json`? for example, writing a module so adding this at the top of the script would work:

```
try:
  import pysimdjson as json
except:
  import json
```

We can also fall back to the built-in json module to handle unimplemented sections for the time being. 

Thanks for the good project :+1:

**Comment by TkTech** [comment]
I'm leaning towards no at the moment, but leaving this open for further comments.

Unlike most other similar libraries (`ijson`, `ujson`, etc), `simdjson` isn't a general-purpose JSON library. Using it requires keeping certain limitations in mind. Providing a compatible API for things like JSONDecoder hooks would absolutely tank performance.
