### ISSUE TITLE
Consider updating to latest release (0.1.2)

### ISSUE THREAD

**Issue by lemire** [TkTech/pysimdjson#25]
It fixes a few potential buffer overruns for adversarial inputs. It should be safer.

**Comment by TkTech** [comment]
👍 going to try to automate the process, since I can watch for new tags matching `v([0-9]+)\.([0-9]+)(?:\.([0-9]+))`, clone, aggregate, test, push (but require manual intervention to tag as a release).

**Comment by lemire** [comment]
I do not plan to bug you too much and automation is good... 

In this instance, we fixed actual bugs... some of them could lead to application crashes... so there is some importance to the update.

**Comment by lemire** [comment]
Release 0.2.0 is out, I will create a new issue.
