### ISSUE TITLE
FreeBSD Packaging

### ISSUE THREAD

**Issue by TkTech** [TkTech/pysimdjson#40]
Upstream simdjson has official FreeBSD support as of 0.4. There are some complications for our binary releases however.

- [ ] Our Ci, Github Actions, does not yet support FreeBSD as a hosted or self-hosted host. See https://github.com/actions/runner/issues/385. We'll need to run the builds elsewhere or cross-compile without running tests.
- [ ] There seems to be no equivalent to manylinux for FreeBSD. Hopefully I'm wrong. We'll need to distribute our binary packages through the native FreeBSD package manager.

**Comment by lemire** [comment]
Cirrus supports freebsb and they allow releasing assets... 

https://cirrus-ci.org/examples/#release-assets

**Comment by TkTech** [comment]
Closing until ABI platform tags are expanded and support lands in pip, see #44. For now, we ensure we work on FreeBSD from source.
