### ISSUE TITLE
FreeBSD & Windows ARM Binary Packages Tracking Issue

### ISSUE THREAD

**Issue by TkTech** [TkTech/pysimdjson#44]
Time to start supporting ARM. Unfortunately we can't use self-hosted runners for ARM because we accept public PRs and I don't feel like having my AWS runner hijacked! We'll be using something other than GitHub actions for Ci on ARM platforms.

- [x] Linux
  - [x] CPython
  - [x] PyPy3 (currently not available on travis.ci for ARM)
- [ ] FreeBSD (no manylinux equivalent, can we even do this? #40)
  - [ ] CPython
- [ ] Windows ARM
  - [ ] CPython
- [x] OS X
  - [x] CPython

Windows ARM support is a bit of an exotic stretch goal. The development ecosystem for Windows ARM is very, very new.
Likewise, OS X ARM support is likely to appear sometime late this year. It's likely Apple will release a new toolchain long before they start shipping hardware.

**Comment by martin-g** [comment]
You can use Drone.io or TravisCI for the ARM build.
Or you can use Docker+QEMU on any CI service: https://medium.com/@martin.grigorov/building-linux-packages-for-different-cpu-architectures-with-docker-and-qemu-d29e4ebc9fa5

**Comment by TkTech** [comment]
PyPy3 for ARM needs to be built from source on travis, missing from package repos for bionic.

**Comment by TkTech** [comment]
CPython linux wheels now available for 3.5-3.8 on ARM64 as of v2.4.

**Comment by TkTech** [comment]
Both Windows and OS X arm builds are doable (and can be built cross-target from existing Ci).
FreeBSD is a no-go until the standard for platform compatibility tags is expanded. See https://packaging.python.org/specifications/platform-compatibility-tags/.

**Comment by TkTech** [comment]
cibuildwheel now supports Widnows ARM as an experimental target. BSD support is unlikely to come in the next few years.
