### ISSUE TITLE
Segfault when not assigning the parser to a variable

### ISSUE THREAD

**Issue by palkeo** [TkTech/pysimdjson#53]
Here is a Python session that segfaults:
```
>>> import simdjson
>>> pa=simdjson.Parser().parse('{"a": 9999}')
>>> pa["a"]
zsh: segmentation fault (core dumped)  python
```

And here is one that works:
```
>>> import simdjson
>>> p = simdjson.Parser()
>>> pa = p.parse('{"a": 9999}')
>>> pa["a"]
9999
```

It's unclear to me why the first one segfaults, and it looks like a bug?

I imagine the parser is garbage collected by Python in the first example, but it's still clearly in use by the "pa" variable?

**Comment by lemire** [comment]
In simdjson, the DOM is owned by the parser. If the parser is no longer available, then the DOM is gone.

**Comment by palkeo** [comment]
Your comment seems to confirm my understanding: the DOM points to the parser. So as long as the DOM points to it, the parser should not be garbage collected from memory.

I understand in the underlying library it's your responsibility. But this is a Python binding, so it should track the life time of the objects created so they get garbage collected properly by Python when not in use anymore.

To put it another way, I think it's a bug to have a Python module make the whole process crash, regardless of how wrong you use it (a binding should raise a Python exception).

**Comment by TkTech** [comment]
It is a bug, a `py::keep_alive<0, 1>()` is needed. Originally, `parse()` only ever returned a full JSON dictionary, and so the keep alive was not necessary. Now that it returns lazy objects that reference the parser, it needs to keep it alive.

**Comment by TkTech** [comment]
Bugfix release tomorrow or late this evening.

**Comment by nelhage** [comment]
Any updates here? I can confirm in local testing that this patch fixes it, although I'm not sure if it might be undesirable in some other way:

```diff
diff --git a/simdjson/binding.cpp b/simdjson/binding.cpp
index 2c17372..459241e 100644
--- a/simdjson/binding.cpp
+++ b/simdjson/binding.cpp
@@ -361,6 +361,7 @@ PYBIND11_MODULE(csimdjson, m) {
             },
             py::arg("s"),
             py::arg("recursive") = false,
+            py::keep_alive<0, 1>(),
             "Parse a JSON document from the byte string `s`.\n"
             "\n"
             ":param s: The document to parse.\n"
```

**Comment by TkTech** [comment]
It's not the only method that can return objects. Anything that can return an Array or Object also needs to handle lifetime.

That method also shouldn't have an unconditional keep alive, because it sometimes just returns a primitive object (recursive=true).

The conditional bit is what is taking so long, as pybind isn't terribly well documented.

**Comment by TkTech** [comment]
This is now fully resolved, with none of the original drawbacks.

**Comment by oflannabhra** [comment]
With these changes, I'm starting to get some `RuntimeError`s (specifically, [this one](https://github.com/TkTech/pysimdjson/blob/1145be6cac70ed065f2053977d470f3f771ac6a0/simdjson/csimdjson.pyx#L437)) where I previously didn't. I understand that this is probably revealing an issue with my code I was unaware of, but is there a good guideline for how to manage the `Object`s and `Array`s that parsing creates? Doing something like manually calling `del my_parsed_object` seems very un-Pythonic.

**Comment by TkTech** [comment]
@oflannabhra do you have an example of how you're using it? See #82 for discussion.
