### ISSUE TITLE
Include License in release

### ISSUE THREAD

**Issue by CJ-Wright** [TkTech/pysimdjson#55]
Would it be possible to include the code's license in the pypi releases? That would help downstream packagers, like conda-forge.

**Comment by TkTech** [comment]
@CJ-Wright Do you need this in any particular format, or just the LICENSE file included in the _MANIFEST.in_, which will put it at the root of the wheel?

**Comment by CJ-Wright** [comment]
No particular format, just a copy of it in the source distribution. To some extent this is less of an issue for me at this point, since we're using the tarball from github.
