### ISSUE TITLE
Support negative array subscripts in query syntax.

### ISSUE THREAD

**Issue by TkTech** [TkTech/pysimdjson#6]
Currently when using a query path you can only retrieve an entire list (ex: `.results[].id`), which is sub-optimal. We should support the typical python slice syntax:

- [x] `.results[0].id` (single) - first element (added in 43e2f2d)
- [x] `.results[:2].id` (array) - first 2 elements (added in 43e2f2d)
- [ ] `.results[-2:].id` (array) - last 2 elements.

**Comment by kootenpv** [comment]
I was bitten by this... an example jsonpath_rw string that I used was `[0].variants.[1].isInStock`, maybe that adds inspiration. I really hope the performance of this library will kick its ass :)

**Comment by TkTech** [comment]
43e2f2d adds support for this, you'd write that query as: `.[0].variants[1].isInStock` which will return a singular `True` or `False`.

Will be pushed to master and pypi soon.

**Comment by kootenpv** [comment]
Sweet! I've tried the latest... for just returning a boolean out of some medium-sized JSON, this was a 780x speedup for me.

**Comment by TkTech** [comment]
We're deprecating this in favor of the builtin JSON-path support in simdjson added a few versions ago.
