### ISSUE TITLE
Access Dictionary Keys Fast

### ISSUE THREAD

**Issue by william-silversmith** [TkTech/pysimdjson#61]
Hi! I have a JSON parsing problem where I am downloading 100k+ files and JSON parsing is taking about 74% of the time (in one sample) to process them excluding download time. I was looking at alternative SIMD JSON parsers to help reduce the burden of parsing as processing is taking somewhere between hours to tens of hours. The files look like:

```
{
    '12291084214': [ 6x int ],
    '19204192141': [ 6x int ],
     ...
}
```

The left hand side represents labels I need to accumulate and the right hand size represents a 3D bounding box. The right hand value side is not useful in the case where I consider the whole dataset and so can be ignored when working on the worst case of the problem. The left hand key side must be decoded and extracted in all cases. Is there a way to use something similar to the `at` method to rapidly extract only the keys?

As an alternative approach, I tried parsing all the files at once which reduces parsing time by about 30%, but results in huge memory usage. I figured there must be a useful middle ground where we can reduce the cost but retain online-processing. ^_^

This process is run infrequently and so it's not the end of the world if such a thing isn't possible, but jeez would it help:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/2517065/97403730-55180f80-18cb-11eb-875a-a39428acecb7.png">

**Comment by TkTech** [comment]
The proxy Object, https://pysimdjson.tkte.ch/native.html#simdjson.Object, has a `.keys()` iterator.

**Comment by william-silversmith** [comment]
Thank you for your help! Sorry for not noticing the docs website. We went from an impractical number of hours to about 20 min. ^_^

**Comment by TkTech** [comment]
Not a problem, it should be front and centre in the README. I will make it more obvious.

**Comment by TkTech** [comment]
Added a "Latest docs" blurb to the top of the README. Hopefully helps others in the future.
