### ISSUE TITLE
Bundle pybind11

### ISSUE THREAD

**Issue by TkTech** [TkTech/pysimdjson#62]
Even though pip's logs show that it is downloading the binary wheel, it's still occasionally requiring pybind11. Since this has happened a few times (for example most recently with https://github.com/alex/nyt-2020-election-scraper/issues/177#issuecomment-723253931), we either need to:

- figure out why this is happening
- bundle the pybind11 headers always, which are a couple of kb.

**Comment by ahartikainen** [comment]
pip first downloads/builds all the binaries and then installs them.

So in your case `pybind11` is a build time dependency that can not be installed at the same step as the package is installed.

    pip install '.[dev]' 

I would create a couple of requirements files: e.g `requirements-dev.txt` and then install them manually in CI

    pip install -r requirements-dev.txt

These can be added to the setup.py with a function. See https://github.com/arviz-devs/arviz/blob/master/setup.py
