### ISSUE TITLE
Python 3.9 Binaries

### ISSUE THREAD

**Issue by william-silversmith** [TkTech/pysimdjson#63]
Hi all,

I just wanted to check in to see when py39 binaries might be available. No rush, I'm just trying to make sure my libraries are ready for when usage picks up and pysimdjson is a dependency.

Thanks for all the help and a great library!

Thanks!
Will

**Comment by TkTech** [comment]
They will be live on PyPi for all platforms once the action finishes in a few minutes.

**Comment by william-silversmith** [comment]
Thank you so much!

Will
