### ISSUE TITLE
This parser can't support a document that big

### ISSUE THREAD

**Issue by dclong** [TkTech/pysimdjson#70]
I encounter the following issue when parsing a huge (>10G) JSON file. 

![image](https://user-images.githubusercontent.com/824507/101207905-31608b80-3626-11eb-8254-2e06b671a4e9.png)

**Comment by lemire** [comment]
How big is report.json?

**Comment by dclong** [comment]
About 13G.

**Comment by lemire** [comment]
The underlying library will refuse to parse JSON documents larger than 4 GB. It will support large inputs, but only if they are made of a stream of JSON documents (e.g., ndjson).

Ingesting a single 13 GB document all at once in a DOM tree is a performance and interoperability anti-pattern. I recommend against it.

I cannot speak pysimdjson but I expect that it works as is expected.

**Comment by TkTech** [comment]
As Lemire said, this isn't supported in the underlying library. When/if simdjson gets streaming support, we'll definitely implement it.
