### ISSUE TITLE
Adding typing support

### ISSUE THREAD

**Issue by kornicameister** [TkTech/pysimdjson#75]
Hey everyone,

it is just a simple question :).
Would like to know if you are interested in either of those:

- adding `py.typed` and  `simdjson.pyi` to describe API for `mypy` or similar
- accepting PR with the same
- having a PR submitted to external [typeshed[(https://github.com/python/typeshed)

**Comment by TkTech** [comment]
Typing would be happily accepted, but should be branched off of #74 rather than the master branch.

**Comment by kornicameister** [comment]
No worries, I can submit initial code I've just used in my project against that branch?
I am assuming you're fine with having it repository then?
