### ISSUE TITLE
collections.abc inheritance for simdjson.Object and simdjson.Array

### ISSUE THREAD

**Issue by chutz** [TkTech/pysimdjson#77]
It would frequently be useful if these objects inherited from the standard collections abstract classes, that way generic `isinstance` tests could work as expected.

My suggestions:
- `simdjson.Object`: `collections.abc.Mapping`
- `simdjson.Array`: `collections.abc.Sequence`, `collections.abc.Iterable`

I could probably take a stab at this if it's something that would be accepted.

**Comment by TkTech** [comment]
See the changes in #74. Specifically,

- count() and index() intentionally removed from Array. This means we don't comply with the collections.abc.Sequence interface, but if you were calling count() or index(), it means you're visiting every element and it would have been faster to just call as_list.

I originally wanted the same as you, but if you're using Array and Object as you would a `list` and `dict` you're not using them efficiently.

**Comment by TkTech** [comment]
Since there's been no further discussion around this, I'm going to ahead and close it but feel free to re-open if you think you have a good way to mix behaviours without encouraging poor performance. I'd definitely *like* for them to be ABC subclasses if we can get away with it!
