### ISSUE TITLE
This parser can't support a document that big

### ISSUE THREAD

**Issue by brianmingus2** [TkTech/pysimdjson#86]
ubuntu@ip-172-31-16-166:~$ time python convert-to-pickle.py
Traceback (most recent call last):
  File "convert-to-pickle.py", line 10, in <module>
    data = simdjson.loads(ch.read())
  File "/usr/local/lib/python3.8/dist-packages/simdjson/__init__.py", line 52, in loads
    return parser.parse(s, True)
  File "simdjson/csimdjson.pyx", line 468, in csimdjson.Parser.parse
ValueError: This parser can't support a document that big

**Comment by lemire** [comment]
The simdjson library is limited to document up to 4 gigabytes. It is also possible to specify your own (lesser) limit and get the same error.

**Comment by lemire** [comment]
As a side-note... if you are routinely working with single JSON files that are larger than 4 GB, you may want to revise your designs. I would consider it a sign that something is amiss. Consider fragmenting your data.

**Comment by brianmingus2** [comment]
I routinely work with JSON datasets larger than 1TB.

**Comment by lemire** [comment]
@brianmingus2 

> I routinely work with JSON datasets larger than 1TB.

Do you mean a single JSON document that spans more than a terabyte or do you mean a set of JSON documents which together span more than a terabyte?

The MongoDB folks have terabytes of JSON, but they are made of many documents (each corresponding to an entry), often written in sequence within a single file/blob, and all of it is usually sharded into many files/blog.

**Comment by brianmingus2** [comment]
I don't have a single JSON file 1TB. The other day I had one at 18GB. I either load it up into RAM, or use Dask.

**Comment by lemire** [comment]
@brianmingus2 Thanks.


My experience with data engineering in general suggests that most JSON data gets serialized as ndjson or JSON-line.

The dask documentation seems to agree with my experience: 

> orient is ‘records’ by default, with lines=True; this is appropriate for line-delimited “JSON-lines” data, the kind of JSON output that is most common in big-data scenarios, and which can be chunked when reading https://docs.dask.org/en/latest/generated/dask.dataframe.read_json.html

>  orient is ‘records’ by default, with lines=True; this produces the kind of JSON output that is most common in big-data applications, and which can be chunked when reading https://docs.dask.org/en/latest/generated/dask.dataframe.to_json.html

The simdjson library supports this mode which dask calls "JSON-lines" for virtually infinite file sizes, with fixed memory usage and parallel (threaded) processing.

See https://github.com/simdjson/simdjson/blob/master/doc/iterate_many.md and https://github.com/TkTech/pysimdjson/issues/71

I realize that it might not be what you are using. Nevertheless, that's how we approach this need in simdjson. We worked hard on our support for ndjson and should you ever use it, we hope you will find that it works well.

**Comment by lemire** [comment]
@brianmingus2 My expectation is that if you have a long collection of records, you often want to avoid loading them in RAM all at once. I would consider that a performance anti-pattern. That is why simdjson offers a different API for collections of records (ndjson) where you 'stream' through, loading only one record in RAM at once.

**Comment by brianmingus2** [comment]
It's not an antipattern.

Remember that you are pushing the difficulty of implementing a better parser onto the customer. They will spend huge amounts more effort in orchestrating their data than would be invested in an automatic memory managed parser.

**Comment by lemire** [comment]
> Remember that you are pushing the difficulty of implementing a better parser onto the customer. 

I am not pushing anything on anyone.

**Comment by brianmingus2** [comment]
You advocated that using JSON files larger than 4GB is an anti-pattern. It’s not. The limit is still in place because writing the parser is hard, and it’s easier to say >4GB is an anti-pattern.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lemire** [comment]
@brianmingus2 The limit is in place because I consider that a single JSON file greater than 4 GB loaded in RAM at once is a performance anti-pattern.

**Comment by brianmingus2** [comment]
That’s not true. I use instances with 24TB of RAM and massive dictionaries. It must be because it would be hard to support, and it’s easier to advocate. The real anti-pattern is the separation of disk and RAM advocated by IBM Sales Engineers in the early days of computing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lemire** [comment]
@brianmingus2 Let me specify that there is nothing wrong with gigabyte-long files, as long as they can be loaded in small chunks, as in line-delimited JSON files. What I recommend against are monolithic large data blobs (many gigabytes) that must be loaded all at once in RAM.


> I use instances with 24TB of RAM and massive dictionaries.

Yes. I understand that you or your employer is paying for the most expensive cloud instances to get the work done. In such scenarios, I agree that the concerns that I have become somewhat irrelevant.

**Comment by brianmingus2** [comment]
It’s not about price. It’s about performance. File size is irrelevant. The only thing that matters is  speed. You must remove the disk from the equation as soon as possible and get the job done.

As I said earlier, advocating that people literally reshape their data so you don’t have to write a more sophisticated parser, causes a lot more work for the customer. That’s the only pattern relevant here.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by anishpdoshi** [comment]
Not sure if this is related, but any suggestions on parsing a response stream? I have a URL that return a very large (~10s of GBs) response, it would be nice to use simdjson to parse it iteratively but not sure how

**Comment by TkTech** [comment]
It's not currently possible with simdjson if it's a single document. Is it JSON, or multiple documents separated by newlines?

**Comment by anishpdoshi** [comment]
Gotcha. It's a single document that isn't newline separated unfortunately. Just a stream of bytes.
