### ISSUE TITLE
Add support to release Linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [TkTech/pysimdjson#88]
Problem
---------
On aarch64, ‘pip install pysimdjson’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi. 

Resolution
-----------
On aarch64, ‘pip install pysimdjson’ should download the wheels from pypi 

@TkTech and Team Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by TkTech** [comment]
Definitely interested in supporting this, however we also need support for aarch64 in the tests.

**Comment by odidev** [comment]
> Definitely interested in supporting this, however we also need support for aarch64 in the tests.

I have added support in the tests for aarch64. Could you please review.

**Comment by TkTech** [comment]
Hi @odidev, as of version 4.0.3, binary wheels are now available for ARM64 as well as PowerPC. On Linux, they're available for both manylinux and musl (Alpine).
