### ISSUE TITLE
Thread safe Parser?

### ISSUE THREAD

**Issue by gingerwizard** [TkTech/pysimdjson#91]
Can we assume the parser is thread safe and can be used by multiple threads concurrently for `parse`?

**Comment by lemire** [comment]
In simdjson, you should have a distinct parser instance per thread.

**Comment by TkTech** [comment]
I've reopened this because at the python level, we can prevent people from shooting themselves in the foot and using a parser across threads. We can't stop someone whose using ctypes or or otherwise interacting from C land but it's better than nothing.
