### ISSUE TITLE
simdjson 2.0.1 does not compile with GCC 8

### ISSUE THREAD

**Issue by watersaber** [TkTech/pysimdjson#97]
simdjson 2.0.1 does not compile with GCC 8. The issue was[ fixed in 2.0.3](https://github.com/simdjson/simdjson/pull/1832)and pysimdjson need to update at least to that version.

**Comment by harrycis** [comment]
Addressed in https://github.com/TkTech/pysimdjson/pull/98

**Comment by TkTech** [comment]
Released
