### ISSUE TITLE
Unable to serialize simdjson Objects into Pickle

### ISSUE THREAD

**Issue by vovavili** [TkTech/pysimdjson#99]
Hello all!

When I try to serialize `simdjson` Object into Pickle, I get the following error:

`TypeError: self.c_element,self.c_parser cannot be converted to a Python object for pickling`

Would it be possible to add support for serializing/pickling simdjson instances directly, without converting them to `dict`? If not pickling, then at least an ability to serialize into `.json` would be lovely as well.

**Comment by TkTech** [comment]
What are you expecting to get when you pick a `simdjson.Object`? It's an thin wrapper around an unsafe C++ object.

To get a `JSON` representation of a `simdjson.Object`, just use the `.mini` property, which will give you minified JSON for the respective object.

**Comment by vovavili** [comment]
>What are you expecting to get when you pick a simdjson.Object? It's an thin wrapper around an unsafe C++ object.

Unfortunately, I am a beginner in C++. Are there no ways to pickle objects using pybind11/boost-pickle/whatever?

> To get a `JSON` representation of a `simdjson.Object`, just use the `.mini` property, which will give you minified JSON for the respective object.

Would it be possible to add this to documentation?

**Comment by lemire** [comment]
> Are there no ways to pickle objects using pybind11/boost-python/whatever?

Why would you want to serialize a parsed JSON using some ad hoc binary dump ? JSON *is* a serialization format.

**Comment by vovavili** [comment]
> A library like simdjson can parse JSON at gigabytes per second. There are relatively few things that are "much faster" than "gigabytes per second" in computing.

But that doesn't seem to apply to _writing_ JSON to files to the hard disk? As far as I see, simdjson relies on Python's native `json` module to write to .json file, which incurs some performance loss.

**Comment by lemire** [comment]
Don't you already have the JSON file? Why would you need to generate it anew?

**Comment by vovavili** [comment]
Nevermind, I forgot that parsed json is just a `bytes` object. I can just do this, which should be just as performant as pickling the file:
```

from urllib.request import urlopen
import simdjson

READER = simdjson.Parser()

# Downloading
with urlopen(%link%) as link:
    d = READER .parse(link.read())

# Writing cache
with open("cache.json", 'wb') as f:
    f.write(x.mini)

# Reading cache
d = READER.load("cache.json")
```

**Comment by lemire** [comment]
Saving the JSON file, instead of another format, makes your whole architecture simpler and easier to debug.
